import { apiBase, defaultRecords } from './cms.js';
const $ = (s) => document.querySelector(s); const tokenKey = 'csrl-admin-token'; let token = sessionStorage.getItem(tokenKey); let records = []; let selected;
const api = async (url, options = {}) => { const response = await fetch(`${apiBase}${url}`, { ...options, headers: { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Request failed'); return response.status === 204 ? null : response.json(); };
const esc = (x='') => String(x).replace(/[&<>'"]/g, (c) => ({'&':'&amp;','>':'&gt;','&':'&amp;',"'":'&#39;','"':'&quot;'}[c]));
const section = () => $('#section-filter').value;
function list(){ const items=records.filter(x=>x.section===section()).sort((a,b)=>a.order-b.order); $('#item-list').innerHTML=items.map(x=>`<button class="item-row ${selected===x?'active':''}" data-id="${esc(x.id)}"><strong>${esc(x.data.title||x.data.name||x.data.slug||'Home content')}</strong><small>${x.visible?'Visible':'Hidden'} · order ${x.order}</small></button>`).join('')||'<p class="muted">No content yet.</p>'; document.querySelectorAll('.item-row').forEach(b=>b.onclick=()=>{selected=records.find(x=>x.id===b.dataset.id&&x.section===section()); renderEditor();list();}); }
function fields(data){ return Object.entries(data).filter(([k])=>k!=='blocks'&&k!=='report'&&k!=='details').map(([k,v])=>`<label class="${String(v).length>70?'field-wide':''}">${esc(k)}${typeof v==='string'&&v.length>70?`<textarea data-field="${esc(k)}">${esc(v)}</textarea>`:`<input data-field="${esc(k)}" value="${esc(v ?? '')}" />`}</label>`).join(''); }
const typeOptions=['heading','text','image','table','quote','columns','divider'];
function blockEditor(block,i){ const type=block.type||'text'; const content=type==='image'?JSON.stringify({url:block.url||'',alt:block.alt||'',caption:block.caption||''},null,2):type==='columns'?JSON.stringify({left:block.left||'',right:block.right||''},null,2):type==='heading'?block.text||'':type==='quote'?JSON.stringify({text:block.text||'',annotation:block.annotation||''},null,2):type==='section'?JSON.stringify({title:block.title||'',content:block.content||'',lead:!!block.lead},null,2):block.html||block.content||''; return `<div class="block"><div class="block-head"><label>Content type<select data-block-type="${i}">${typeOptions.map(x=>`<option ${x===type?'selected':''}>${x}</option>`).join('')}</select></label><button type="button" data-remove-block="${i}" class="danger">Remove</button></div>${type==='divider'?'<p class="muted">A simple horizontal divider.</p>':`<label>${type==='image'||type==='columns'||type==='quote'?'Content settings (JSON)':'Content'}<textarea data-block-content="${i}">${esc(content)}</textarea></label>`}</div>`; }
function renderEditor(){ if(!selected){$('#editor').innerHTML='<p>Select an item to edit it.</p>';return;} const blocks=selected.data.blocks||selected.data.report||[]; $('#editor').innerHTML=`<h2>${esc(selected.data.title||selected.data.name||selected.id)}</h2><div class="field-grid"><label>URL ID / slug<input id="record-id" value="${esc(selected.id)}" /></label><label>Display order<input id="record-order" type="number" value="${selected.order}" /></label><label><input id="record-visible" type="checkbox" ${selected.visible?'checked':''}/> Show on public website</label>${fields(selected.data)}</div><h3>Content blocks</h3><p class="muted">Choose a type: headings, text, images, tables, quotes (with annotation), or two-column layouts. Text fields accept simple HTML.</p><div id="blocks">${blocks.map(blockEditor).join('')}</div><div class="block-actions"><select id="add-block-type">${typeOptions.map(x=>`<option>${x}</option>`).join('')}</select><button id="add-block" type="button">Add block</button></div><div class="editor-actions"><button id="save-item" class="button dark-button">Save changes</button><button id="delete-item" class="danger">Delete</button></div>`; $('#add-block').onclick=()=>{blocks.push({type:$('#add-block-type').value});selected.data.blocks=blocks;renderEditor();}; document.querySelectorAll('[data-remove-block]').forEach(b=>b.onclick=()=>{blocks.splice(+b.dataset.removeBlock,1);renderEditor();}); $('#save-item').onclick=save; $('#delete-item').onclick=del; }
function blockFrom(type,value){ if(type==='divider')return{type}; if(['image','columns','quote','section'].includes(type)){try{return{type,...JSON.parse(value)}}catch{throw new Error(`${type} settings must be valid JSON.`)}} return type==='heading'?{type,text:value}:{type,html:value}; }
async function save(){try{ const data={...selected.data}; document.querySelectorAll('[data-field]').forEach(el=>data[el.dataset.field]=el.value); const blocks=[]; document.querySelectorAll('[data-block-type]').forEach(el=>{const i=el.dataset.blockType;blocks.push(blockFrom(el.value,document.querySelector(`[data-block-content="${i}"]`)?.value||''));}); if(blocks.length)data.blocks=blocks; const oldId=selected.id; selected={...selected,id:$('#record-id').value.trim(),order:+$('#record-order').value,visible:$('#record-visible').checked,data}; await api(`/api/admin/content/${selected.section}/${encodeURIComponent(selected.id)}`,{method:'PUT',body:JSON.stringify(selected)}); if(oldId!==selected.id)await api(`/api/admin/content/${selected.section}/${encodeURIComponent(oldId)}`,{method:'DELETE'}); const i=records.findIndex(x=>x.section===selected.section&&x.id===oldId); if(i>=0)records[i]=selected;else records.push(selected); list();renderEditor();alert('Saved.');}catch(e){alert(e.message)}}
async function del(){if(!confirm('Delete this content item?'))return;await api(`/api/admin/content/${selected.section}/${encodeURIComponent(selected.id)}`,{method:'DELETE'});records=records.filter(x=>x!==selected);selected=null;list();renderEditor();}
async function boot(){try{const saved=await api('/api/admin/content');records=saved.items; if(!records.length){await api('/api/admin/content/bootstrap',{method:'POST',body:JSON.stringify({items:defaultRecords()})});records=(await api('/api/admin/content')).items;}$('#login-panel').hidden=true;$('#app-panel').hidden=false;list();}catch{sessionStorage.removeItem(tokenKey);token=null;}}
$('#login-form').onsubmit=async(e)=>{e.preventDefault();try{token=(await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target))) })).token;sessionStorage.setItem(tokenKey,token);boot();}catch(err){$('.admin-message').textContent=err.message;}};
$('#section-filter').onchange=()=>{selected=null;list();renderEditor();}; $('#new-item').onclick=()=>{const id=`new-${Date.now()}`;selected={id,section:section(),data:section()==='people'?{name:'New contact person',email:'',role:'',profile:''}:{title:'New content',slug:id,blocks:[]},visible:true,order:records.filter(x=>x.section===section()).length};renderEditor();}; $('#sign-out').onclick=()=>{sessionStorage.removeItem(tokenKey);location.reload();}; $('#image-upload').onchange=async(e)=>{try{const f=e.target.files[0];if(!f)return;const form=new FormData();form.append('file',f);const {url}=await api('/api/admin/upload',{method:'POST',body:form});$('#upload-result').textContent=`Uploaded: ${url} — paste this into an image block.`;}catch(err){$('#upload-result').textContent=err.message;}}; if(token)boot();
