import { apiBase, defaultRecords } from './cms.js';
const $ = (selector) => document.querySelector(selector); const tokenKey = 'csrl-admin-token'; let token = sessionStorage.getItem(tokenKey); let records = []; let selected;
const api = async (url, options = {}) => { const response = await fetch(`${apiBase}${url}`, { ...options, headers: { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Request failed'); return response.status === 204 ? null : response.json(); };
const esc = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
const label = (key) => key.replace(/([A-Z])/g, ' $1').replace(/^./, (x) => x.toUpperCase()); const section = () => $('#section-filter').value;
const types = [['heading', 'Heading'], ['text', 'Text'], ['image', 'Image'], ['table', 'Table'], ['quote', 'Quote with source'], ['columns', 'Two texts side by side'], ['divider', 'Divider']];
function styleFields(style = {}, prefix) { return `<div class="style-fields"><label>Font<select data-style="${prefix}.font"><option value="">Website default</option><option value="sans" ${style.font === 'sans' ? 'selected' : ''}>Modern sans-serif</option><option value="serif" ${style.font === 'serif' ? 'selected' : ''}>Classic serif</option><option value="mono" ${style.font === 'mono' ? 'selected' : ''}>Monospace</option></select></label><label>Text colour<input data-style="${prefix}.color" type="color" value="${/^#[0-9a-f]{6}$/i.test(style.color || '') ? style.color : '#172522'}" /></label><label>Text size <output data-size-output="${prefix}">${style.size || 16}px</output><input data-style="${prefix}.size" type="range" min="12" max="64" value="${style.size || 16}" /></label></div>`; }
function list() { const items = records.filter((item) => item.section === section()).sort((a, b) => a.order - b.order); $('#item-list').innerHTML = items.map((item) => `<button class="item-row ${selected === item ? 'active' : ''}" data-id="${esc(item.id)}"><strong>${esc(item.data.title || item.data.name || item.data.slug || 'Home content')}</strong><small>${item.visible ? 'Visible' : 'Hidden'} · order ${item.order}</small></button>`).join('') || '<p class="muted">No content yet.</p>'; document.querySelectorAll('.item-row').forEach((button) => button.onclick = () => { selected = records.find((item) => item.id === button.dataset.id && item.section === section()); renderEditor(); list(); }); }
function basicFields(data) { return Object.entries(data).filter(([key]) => !['blocks', 'report', 'details'].includes(key)).map(([key, value]) => `<label class="${String(value).length > 70 ? 'field-wide' : ''}">${label(key)}${typeof value === 'string' && value.length > 70 ? `<textarea data-field="${esc(key)}">${esc(value)}</textarea>` : `<input data-field="${esc(key)}" value="${esc(value ?? '')}" />`}</label>`).join(''); }
function blockEditor(block, index) { const type = block.type || 'text'; const style = block.style || {}; const head = `<div class="block-head"><label>Display type<select data-block-type="${index}">${types.map(([value, name]) => `<option value="${value}" ${value === type ? 'selected' : ''}>${name}</option>`).join('')}</select></label><button type="button" data-remove-block="${index}" class="danger">Remove</button></div>`; let content = '';
  if (type === 'heading') content = `<label>Heading text<input data-block="${index}.text" value="${esc(block.text)}" /></label><label>Heading size<select data-block="${index}.level"><option value="h2" ${block.level === 'h2' ? 'selected' : ''}>Large</option><option value="h3" ${block.level === 'h3' ? 'selected' : ''}>Medium</option><option value="h4" ${block.level === 'h4' ? 'selected' : ''}>Small</option></select></label>${styleFields(style, `${index}.style`)}`;
  if (type === 'text') content = `<label>Text<textarea data-block="${index}.text">${esc(block.text ?? block.html ?? block.content ?? '')}</textarea></label>${block.html || block.content ? '<p class="muted">This is older formatted content. Saving changes converts it to simple editable text.</p>' : ''}${styleFields(style, `${index}.style`)}`;
  if (type === 'image') content = `<label>Image address<input data-block="${index}.url" value="${esc(block.url)}" placeholder="Paste the uploaded image address" /></label><label>Image description<input data-block="${index}.alt" value="${esc(block.alt)}" /></label><label>Caption<input data-block="${index}.caption" value="${esc(block.caption)}" /></label>`;
  if (type === 'table') content = `<label>Column titles <span class="muted">Separate titles with |</span><input data-block="${index}.headers" value="${esc((block.headers || []).join(' | '))}" placeholder="Test | Result" /></label><label>Rows <span class="muted">One row per line; separate cells with |</span><textarea data-block="${index}.rows" placeholder="Cube 1 | 32 MPa">${esc((block.rows || []).map((row) => row.join(' | ')).join('\n'))}</textarea></label>`;
  if (type === 'quote') content = `<label>Quote<textarea data-block="${index}.text">${esc(block.text)}</textarea></label><label>Source / annotation<input data-block="${index}.annotation" value="${esc(block.annotation || block.attribution)}" /></label>${styleFields(style, `${index}.style`)}`;
  if (type === 'columns') content = `<div class="field-grid"><label>Left-side text<textarea data-block="${index}.left">${esc(block.left)}</textarea></label><label>Right-side text<textarea data-block="${index}.right">${esc(block.right)}</textarea></label></div>${styleFields(style, `${index}.style`)}`;
  if (type === 'divider') content = '<p class="muted">A horizontal line used to separate content.</p>';
  return `<div class="block">${head}${content}</div>`; }
function readStyle(prefix) { const get = (name) => document.querySelector(`[data-style="${prefix}.${name}"]`)?.value; return { font: get('font') || undefined, color: get('color'), size: Number(get('size')) || undefined }; }
function readBlock(_block, index) { const get = (key) => document.querySelector(`[data-block="${index}.${key}"]`)?.value || ''; const type = document.querySelector(`[data-block-type="${index}"]`).value; if (type === 'divider') return { type }; if (type === 'heading') return { type, text: get('text'), level: get('level'), style: readStyle(`${index}.style`) }; if (type === 'text') return { type, text: get('text'), style: readStyle(`${index}.style`) }; if (type === 'image') return { type, url: get('url'), alt: get('alt'), caption: get('caption') }; if (type === 'table') return { type, headers: get('headers').split('|').map((x) => x.trim()).filter(Boolean), rows: get('rows').split('\n').filter(Boolean).map((row) => row.split('|').map((cell) => cell.trim())) }; if (type === 'quote') return { type, text: get('text'), annotation: get('annotation'), style: readStyle(`${index}.style`) }; return { type, left: get('left'), right: get('right'), style: readStyle(`${index}.style`) }; }
function renderEditor() { if (!selected) { $('#editor').innerHTML = '<p>Select an item to edit it.</p>'; return; } const blocks = selected.data.blocks || selected.data.report || []; $('#editor').innerHTML = `<h2>${esc(selected.data.title || selected.data.name || selected.id)}</h2><div class="field-grid"><label>Website address / ID<input id="record-id" value="${esc(selected.id)}" /></label><label>Display order<input id="record-order" type="number" value="${selected.order}" /></label><label><input id="record-visible" type="checkbox" ${selected.visible ? 'checked' : ''}/> Show on public website</label>${basicFields(selected.data)}</div><h3>Page content</h3><p class="muted">No coding required. Choose a display type, fill in the fields, and use the controls to choose each text’s font, colour, and size.</p><div id="blocks">${blocks.map(blockEditor).join('')}</div><div class="block-actions"><select id="add-block-type">${types.map(([value, name]) => `<option value="${value}">${name}</option>`).join('')}</select><button id="add-block" type="button">Add content</button></div><div class="editor-actions"><button id="save-item" class="button dark-button">Save changes</button><button id="delete-item" class="danger">Delete</button></div>`;
  $('#add-block').onclick = () => { blocks.push({ type: $('#add-block-type').value }); selected.data.blocks = blocks; renderEditor(); }; document.querySelectorAll('[data-remove-block]').forEach((button) => button.onclick = () => { blocks.splice(+button.dataset.removeBlock, 1); renderEditor(); }); document.querySelectorAll('[data-block-type]').forEach((select) => select.onchange = () => { blocks[+select.dataset.blockType] = { type: select.value }; renderEditor(); }); document.querySelectorAll('[data-style$=".size"]').forEach((input) => input.oninput = () => { document.querySelector(`[data-size-output="${input.dataset.style.replace('.size', '')}"]`).textContent = `${input.value}px`; }); $('#save-item').onclick = save; $('#delete-item').onclick = remove; }
async function save() { try { const data = { ...selected.data }; document.querySelectorAll('[data-field]').forEach((input) => data[input.dataset.field] = input.value); const existing = data.blocks || data.report || []; data.blocks = existing.map(readBlock); delete data.report; delete data.details; const oldId = selected.id; selected = { ...selected, id: $('#record-id').value.trim(), order: +$('#record-order').value, visible: $('#record-visible').checked, data }; await api(`/api/admin/content/${selected.section}/${encodeURIComponent(selected.id)}`, { method: 'PUT', body: JSON.stringify(selected) }); if (oldId !== selected.id) await api(`/api/admin/content/${selected.section}/${encodeURIComponent(oldId)}`, { method: 'DELETE' }); const index = records.findIndex((item) => item.section === selected.section && item.id === oldId); if (index >= 0) records[index] = selected; else records.push(selected); list(); renderEditor(); alert('Saved.'); } catch (error) { alert(error.message); } }
async function remove() { if (!confirm('Delete this content item?')) return; await api(`/api/admin/content/${selected.section}/${encodeURIComponent(selected.id)}`, { method: 'DELETE' }); records = records.filter((item) => item !== selected); selected = null; list(); renderEditor(); }
async function boot() { try { const saved = await api('/api/admin/content'); records = saved.items; if (!records.length) { await api('/api/admin/content/bootstrap', { method: 'POST', body: JSON.stringify({ items: defaultRecords() }) }); records = (await api('/api/admin/content')).items; } $('#login-panel').hidden = true; $('#app-panel').hidden = false; list(); } catch { sessionStorage.removeItem(tokenKey); token = null; } }
$('#login-form').onsubmit = async (event) => { event.preventDefault(); try { token = (await api('/api/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) })).token; sessionStorage.setItem(tokenKey, token); boot(); } catch (error) { $('.admin-message').textContent = error.message; } };
$('#section-filter').onchange = () => { selected = null; list(); renderEditor(); }; $('#new-item').onclick = () => { const id = `new-${Date.now()}`; selected = { id, section: section(), data: section() === 'people' ? { name: 'New contact person', email: '', role: '', profile: '' } : { title: 'New content', slug: id, blocks: [] }, visible: true, order: records.filter((item) => item.section === section()).length }; renderEditor(); }; $('#sign-out').onclick = () => { sessionStorage.removeItem(tokenKey); location.reload(); }; $('#image-upload').onchange = async (event) => { try { const file = event.target.files[0]; if (!file) return; const form = new FormData(); form.append('file', file); const { url } = await api('/api/admin/upload', { method: 'POST', body: form }); $('#upload-result').textContent = `Uploaded: ${url}. Copy this into the image address field.`; } catch (error) { $('#upload-result').textContent = error.message; } }; if (token) boot();
