// CONTENT EDITOR: Replace sample text and image URLs here. Copy a project,
// news item, or person object to add another entry without changing layouts.
// The *Content fields accept HTML for paragraphs, images, tables, and equations.
export const siteContent = {
  about: {
    title: "In coordination with Bheri Babai Diversion Multipurpose Project (BBDMP)",
    copy: "Primary research focus on safety, efficiency, and environmental performance of the construction industry. Our lab works are focused on material behavior, concrete technology and steel structures, sustainable infrastructures and circular economy."
  },
  news: [
    { slug: "hybrid-framework", date: "1 Oct 2026", type: "Publication", title: "Learning at BBDMP", image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=85", details: "<p>Our latest publication presents a performance-based framework for selecting hybrid steel-concrete member configurations. It considers material efficiency, constructability, strength, serviceability, and life-cycle impact together.</p><p>The work gives designers a transparent way to compare early-stage alternatives before a preferred structural scheme is fixed.</p><h2>Research focus</h2><p>The team is now extending the framework with experimental calibration and case-study applications for regional building practice.</p>" },
    { slug: "cyclic-frame", date: "29 Sep 2026", type: "INTERNSHIP", title: "Completion of 6 weeks of internship at BBDMP : Kathmandu University (KU) Students", image: "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1000&q=85", details: "<p>The lab has commissioned a servo-controlled cyclic loading frame for testing structural components under realistic reversing loads. The system expands our capacity for beam-column, wall, connection, and strengthening studies.</p><p>Its programmable loading protocols will support repeatable quasi-static tests, while the synchronized data-acquisition system records force, displacement, strain, and image-based measurements.</p><h2>What this enables</h2><ul><li>Large-scale component tests with controlled cyclic displacement histories.</li><li>Closer comparison between laboratory evidence and earthquake design demands.</li><li>Training opportunities for students working in experimental structural engineering.</li></ul>" },
    { slug: "bridge-deck-monitoring", date: "03 Jul 2025", type: "Field notes", title: "From lab to bridge deck: monitoring materials in demanding conditions.", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=85", details: "<p>Field monitoring is helping the lab connect material-scale test results with the conditions experienced by infrastructure in service. The current study follows moisture, temperature, and surface response across changing weather cycles.</p><p>These observations inform laboratory exposure programmes and help prioritize the durability questions that matter most for practical design and maintenance.</p>" },
    { slug: "bridge-deck-monitoring", date: "03 Jul 2025", type: "Field notes", title: "From lab to bridge deck: monitoring materials in demanding conditions.", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=85", details: "<p>Field monitoring is helping the lab connect material-scale test results with the conditions experienced by infrastructure in service. The current study follows moisture, temperature, and surface response across changing weather cycles.</p><p>These observations inform laboratory exposure programmes and help prioritize the durability questions that matter most for practical design and maintenance.</p>" }
  ],
  projects: [
    { slug: "low-carbon-concrete", tag: "Concrete structures", title: "Ductility and damage control in low-carbon reinforced concrete", description: "Quantifying the interaction of low-clinker binders, reinforcement detailing, and cyclic demand in structural components.", abstract: "This project develops design-ready evidence for reinforced concrete systems with reduced embodied carbon.", methodologyContent: "<p>Material characterization, reinforced-column tests, and digital image correlation are combined to connect mixture design with component-level response.</p><table><thead><tr><th>Stage</th><th>Evidence</th></tr></thead><tbody><tr><td>Materials</td><td>Strength, stiffness, and shrinkage</td></tr><tr><td>Components</td><td>Drift capacity and damage patterns</td></tr></tbody></table>", objectivesContent: "<p>Establish ductility benchmarks and damage-control guidance for reinforced concrete using lower-carbon binders.</p><ul><li>Compare critical reinforcement details.</li><li>Measure stiffness and strength retention under cyclic demand.</li></ul>", contributionContent: "<p>Practical recommendations for material selection and reinforcement detailing in low-carbon structural elements.</p><p class=\"equation\">Damage index = residual drift / peak drift</p>", image: "https://images.unsplash.com/photo-1562259949-a4c55b73f8e0?auto=format&fit=crop&w=1200&q=85" },
    { slug: "rebar-loading", tag: "Steel and rebar", title: "Rebar performance under complex loading histories", description: "Assessing strength, fatigue, bond, and fracture behavior across modern reinforcing steel products.", abstract: "A test programme linking mill properties to the performance of reinforced concrete assemblies.", methodologyContent: "<p>Tensile testing, bond tests, and low-cycle fatigue establish a clear chain from mill properties to reinforcement response in concrete assemblies.</p>", objectivesContent: "<p>Characterize the effects of repeated and reversing loads on reinforcement and its connection with surrounding concrete.</p>", contributionContent: "<p>A more reliable basis for selecting and detailing reinforcing steel in seismic and fatigue-critical structures.</p>", image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=85" },
    { slug: "hybrid-optimization", tag: "Optimization", title: "Optimization of hybrid structural systems", description: "Using performance-based modelling to reduce material use while preserving safety, constructability, and service life.", abstract: "Parametric design methods for efficient composite steel and concrete systems.", methodologyContent: "<p>Finite element modelling, reliability analysis, and life-cycle assessment are used to test feasible hybrid system configurations.</p>", objectivesContent: "<p>Identify hybrid system configurations that reduce material intensity without compromising structural performance.</p>", contributionContent: "<p>Design workflows that reveal lower-carbon, buildable options early in the engineering process.</p>", image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=85" },
    { slug: "circular-aggregates", tag: "Sustainable materials", title: "Circular aggregates for resilient infrastructure", description: "Evaluating recycled aggregates and industrial by-products in durable, locally appropriate concrete mixtures.", abstract: "Practical pathways for circular mineral resources in infrastructure construction.", methodologyContent: "<p>Mix design, durability testing, and environmental assessment examine the practical use of circular mineral resources.</p>", objectivesContent: "<p>Measure how circular mineral resources affect concrete strength, durability, and life-cycle impacts.</p>", contributionContent: "<p>Locally relevant mix-design guidance for durable concrete with reduced virgin material demand.</p>", image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=85" }
  ],
  people: [
    { initials: "DT", name: "Er. Dipesh Tiwari", role: "Lab Director | Research Engineer | Concrete and Steel Structures | FEM | Construction Technology ", email: "dipesh.bbdmp2025@gmail.com", photo: "https://github.com/bridge4er-startup/CSRL/blob/main/Contact%20Photos/Dipesh.png", profile: "M.Sc. in Structural Engineering, Lead experimental and analytical research on reinforced concrete and prestressed structures, Structural Health Monitoring, Resilient Infrastructure, Finite Element Analysis and design guidance." },
    { initials: "SB", name: "Er. Sudeep Bhusal ", role: "Research Engineer | Concrete and Steel Structures | Construction Technology ", email: "sudeepbhusal@gmail.com", photo: "https://github.com/bridge4er-startup/CSRL/blob/main/Contact%20Photos/Sudeep.jpeg", profile: "Coordinate structural testing programmes, instrumentation, and data quality across steel and reinforced-concrete projects." },
    { initials: "SD", name: "Er. Sumi Dhakal", role: "Research Engineer | Concrete and Steel Structures | Construction Technology", email: "msumidhakal@gmail.com", photo: "https://github.com/bridge4er-startup/CSRL/blob/main/Contact%20Photos/Sumi.jpeg", profile: "Coordinate all laboratory works, develop research programs related with optimization and reliability methods for sustainable construction techniques." },
    { initials: "AC", name: "Ashok Chaudhary", role: "Lab Technician | Materials", email: "+977 9823097170", photo: "Blank", profile: "Perform Lab Tests, Management and Maintenance Works" }
  ],
  contact: { email: "bridge4er@gmail.com" }
};
