// CONTENT EDITOR: Replace sample text and image URLs here. Copy a project,
// news item, or person object to add another entry without changing layouts.
// The *Content fields accept HTML for paragraphs, images, tables, and equations.
export const siteContent = {
  about: {
    title: "We investigate the structures that hold our communities together.",
    copy: "Civil Structures Research Lab advances the safety, efficiency, and environmental performance of the built environment. Our work moves from material behavior to infrastructure-scale structural systems."
  },
  news: [
    { slug: "cyclic-frame", date: "12 Sep 2025", type: "Lab update", title: "New cyclic loading frame commissioned for large-scale component testing.", image: "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1000&q=85", details: "<p>The lab has commissioned a servo-controlled cyclic loading frame for testing structural components under realistic reversing loads. The system expands our capacity for beam-column, wall, connection, and strengthening studies.</p><p>Its programmable loading protocols will support repeatable quasi-static tests, while the synchronized data-acquisition system records force, displacement, strain, and image-based measurements.</p><h2>What this enables</h2><ul><li>Large-scale component tests with controlled cyclic displacement histories.</li><li>Closer comparison between laboratory evidence and earthquake design demands.</li><li>Training opportunities for students working in experimental structural engineering.</li></ul>" },
    { slug: "hybrid-framework", date: "28 Aug 2025", type: "Publication", title: "Team publishes framework for optimization of hybrid steel-concrete members.", image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=85", details: "<p>Our latest publication presents a performance-based framework for selecting hybrid steel-concrete member configurations. It considers material efficiency, constructability, strength, serviceability, and life-cycle impact together.</p><p>The work gives designers a transparent way to compare early-stage alternatives before a preferred structural scheme is fixed.</p><h2>Research focus</h2><p>The team is now extending the framework with experimental calibration and case-study applications for regional building practice.</p>" },
    { slug: "bridge-deck-monitoring", date: "03 Jul 2025", type: "Field notes", title: "From lab to bridge deck: monitoring materials in demanding conditions.", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=85", details: "<p>Field monitoring is helping the lab connect material-scale test results with the conditions experienced by infrastructure in service. The current study follows moisture, temperature, and surface response across changing weather cycles.</p><p>These observations inform laboratory exposure programmes and help prioritize the durability questions that matter most for practical design and maintenance.</p>" }
  ],
  projects: [
    { slug: "low-carbon-concrete", tag: "Concrete structures", title: "Ductility and damage control in low-carbon reinforced concrete", description: "Quantifying the interaction of low-clinker binders, reinforcement detailing, and cyclic demand in structural components.", abstract: "This project develops design-ready evidence for reinforced concrete systems with reduced embodied carbon.", methodologyContent: "<p>Material characterization, reinforced-column tests, and digital image correlation are combined to connect mixture design with component-level response.</p><table><thead><tr><th>Stage</th><th>Evidence</th></tr></thead><tbody><tr><td>Materials</td><td>Strength, stiffness, and shrinkage</td></tr><tr><td>Components</td><td>Drift capacity and damage patterns</td></tr></tbody></table>", objectivesContent: "<p>Establish ductility benchmarks and damage-control guidance for reinforced concrete using lower-carbon binders.</p><ul><li>Compare critical reinforcement details.</li><li>Measure stiffness and strength retention under cyclic demand.</li></ul>", contributionContent: "<p>Practical recommendations for material selection and reinforcement detailing in low-carbon structural elements.</p><p class=\"equation\">Damage index = residual drift / peak drift</p>", image: "https://images.unsplash.com/photo-1562259949-a4c55b73f8e0?auto=format&fit=crop&w=1200&q=85" },
    { slug: "rebar-loading", tag: "Steel and rebar", title: "Rebar performance under complex loading histories", description: "Assessing strength, fatigue, bond, and fracture behavior across modern reinforcing steel products.", abstract: "A test programme linking mill properties to the performance of reinforced concrete assemblies.", methodologyContent: "<p>Tensile testing, bond tests, and low-cycle fatigue establish a clear chain from mill properties to reinforcement response in concrete assemblies.</p>", objectivesContent: "<p>Characterize the effects of repeated and reversing loads on reinforcement and its connection with surrounding concrete.</p>", contributionContent: "<p>A more reliable basis for selecting and detailing reinforcing steel in seismic and fatigue-critical structures.</p>", image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=85" },
    { slug: "hybrid-optimization", tag: "Optimization", title: "Optimization of hybrid structural systems", description: "Using performance-based modelling to reduce material use while preserving safety, constructability, and service life.", abstract: "Parametric design methods for efficient composite steel and concrete systems.", methodologyContent: "<p>Finite element modelling, reliability analysis, and life-cycle assessment are used to test feasible hybrid system configurations.</p>", objectivesContent: "<p>Identify hybrid system configurations that reduce material intensity without compromising structural performance.</p>", contributionContent: "<p>Design workflows that reveal lower-carbon, buildable options early in the engineering process.</p>", image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=85" },
    { slug: "circular-aggregates", tag: "Sustainable materials", title: "Circular aggregates for resilient infrastructure", description: "Evaluating recycled aggregates and industrial by-products in durable, locally appropriate concrete mixtures.", abstract: "Practical pathways for circular mineral resources in infrastructure construction.", methodologyContent: "<p>Mix design, durability testing, and environmental assessment examine the practical use of circular mineral resources.</p>", objectivesContent: "<p>Measure how circular mineral resources affect concrete strength, durability, and life-cycle impacts.</p>", contributionContent: "<p>Locally relevant mix-design guidance for durable concrete with reduced virgin material demand.</p>", image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=85" }
  ],
  people: [
    { initials: "AK", name: "Dr. Anisha Koirala", role: "Lab Director | Concrete Structures", email: "anisha.koirala@example.edu", photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=85", profile: "Leads experimental and analytical research on low-carbon reinforced concrete, structural resilience, and evidence-led design guidance." },
    { initials: "RM", name: "Rohan Maharjan", role: "Research Engineer | Steel and Testing", email: "rohan.maharjan@example.edu", photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=85", profile: "Coordinates structural testing programmes, instrumentation, and data quality across steel and reinforced-concrete projects." },
    { initials: "SP", name: "Sanjay Patel", role: "Doctoral Researcher | Optimization", email: "sanjay.patel@example.edu", photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=85", profile: "Develops optimization and reliability methods for efficient hybrid structural systems and lower-impact design decisions." },
    { initials: "NB", name: "Nisha Bista", role: "Research Associate | Materials", email: "nisha.bista@example.edu", photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=700&q=85", profile: "Studies circular aggregates, binder systems, and durability mechanisms for resilient local infrastructure." }
  ],
  contact: { email: "bridge4er@gmail.com" }
};
