import { getSiteContent } from './cms.js';
import { byId, escapeHtml } from './site.js';
const siteContent = await getSiteContent();
const hero = siteContent.home.hero;
byId('hero-eyebrow').textContent = hero.eyebrow;
byId('hero-title').textContent = hero.title;
byId('hero-emphasis').textContent = hero.emphasis;
byId('hero-intro').textContent = hero.copy;
byId('hero-button').href = hero.buttonHref;
byId('hero-button-label').textContent = hero.buttonLabel;
byId('about-title').textContent = siteContent.about.title;
byId('about-copy').textContent = siteContent.about.copy;
byId('news-grid').innerHTML = siteContent.news.map((item, index) => `<article class="news-card ${index === 0 ? 'news-lead' : ''}"><img src="${escapeHtml(item.image)}" alt="" loading="lazy" /><div class="news-copy"><p><span>${escapeHtml(item.type)}</span>${escapeHtml(item.date)}</p><h3>${escapeHtml(item.title)}</h3><a href="/news.html?id=${encodeURIComponent(item.slug)}" aria-label="Read: ${escapeHtml(item.title)}">Read update <span>&#8594;</span></a></div></article>`).join('');
